# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b97b1ae38160de3d980dbb8571ed5f25ad0732244a593adb7bf5b082421764ff3ba830ad15642a3c9a0b66fc48443ee0885120fbdcca1f55c4533204d7a1d2c8

test:
  secret_key_base: d309237b62ca1e053db5df75134d29f77671d596797738204e9ea7077aca7d8cf25328f455cff7ad8dc2ba44855ea40ed70b7e80cd47ff40422a29e76e8431ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
